package com.ferdyJmartDR.jmart_android.model;
/**
 * @author Mochamad Ferdy Fauzan
 * @version 05-12-2021
 */
public enum ProductCategory {
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS, HEALTHCARE, FURNITURE, JEWELRY,
    TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE, PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING
}
